# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0838ba2415a53eaaeedc94871be9f6f9bddb4f27a37c76b2c96f85af6b8ae87fcf0ce5db5978fa73b9b0bda62161b5c94e878b3b453a5b8a5fba3b50aac2339a

test:
  secret_key_base: 47ec46f974f331cdbf9bfcf9e97d38374f5e0664359045d675a02ba33659ce7a16f0a4d9f3779d4645f78e07bef9306eecded5aa8b10959eef2b2a7aa3afaf52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
